// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskManagerApi.Data;

#nullable disable

namespace TaskManagerApi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]

    //Declara la clase captura y hereda de ModelSnapshot, es una herramienta de .Net para gestionar la base de datos
    partial class AppDbContextModelSnapshot : ModelSnapshot 
    {
        protected override void BuildModel(ModelBuilder modelBuilder) //Este metodo dibuja el diseño de la base de datos en la momoria .Net
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63); //No puede pasar de 63 caracteres

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskManagerApi.Modules.Tasks.Entities.TodoTask", b =>
                {
                    //Registra la propiedad id, que es numero entero y que su valor se genera al crear un nuevo registro
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
